# Generated by Django 3.0.9 on 2020-08-04 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reputation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('region', models.CharField(max_length=255)),
                ('bio', models.TextField(default='', max_length=1000)),
                ('reputation', models.IntegerField(default=0)),
                ('user_type', models.IntegerField(choices=[(1, 'Regular'), (2, 'Business'), (3, 'Internal')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
