# Generated by Django 3.0.9 on 2020-08-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200805_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
