# Generated by Django 3.0.9 on 2020-08-08 13:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_thing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.thing_image_file_path),
        ),
    ]
